language: c
compiler:
  - gcc
sudo: false
addons:
  apt:
    packages:
    - check
before_install:
    - pip install --user cpp-coveralls
script:
  - autoreconf -i && ./configure ${FEATURES} --enable-gcov CFLAGS="-g -O0" && make && make check
after_success:
  - coveralls --exclude check --gcov-options '\-lp' -b .
after_failure:
  - cat $(find check -iname '*.log') /dev/null

env:
  matrix:
    - FEATURES=""
    - FEATURES="--with-fixed-allocator"
